name: Python Workspace CI

on:
  push:
  pull_request:

jobs:
  logically:
    uses: leraniode/.github/.github/workflows/python-ci.yml@main
    with:
      package_path: logically

  choco:
    uses: leraniode/.github/.github/workflows/python-ci.yml@main
    with:
      package_path: choco