name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  logically:
    uses: leraniode/.github/.github/workflows/python-ci.yml@main
    with:
      package_path: src/logically

  choco:
    uses: leraniode/.github/.github/workflows/python-ci.yml@main
    with:
      package_path: src/choco